### ISSUE TITLE
Master Release

### ISSUE THREAD

**Issue by Feyzarkt** [Explore-In-HMS/common-mobile-services#87]
Master release issue has a two part:
(done)-> refactor cms version conflicts
-> open Mr dev to master

**Comment by Feyzarkt** [comment]
A solution was found for the deploy_firebase error: instead of the deprecated 'FIREBASE_TOKEN' authentication, a service account key with 'GOOGLE_APPLICATION_CREDENTIALS' must be used by Google Cloud Console.📌📌

**Comment by htk007** [comment]
Remove unnecessary usage of yml configuration for solving block issue to master release
